name: Docker Image CI for GHCR

on:
    push

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build and push the image
              run: |
                docker login --username sohamping --password ${{secrets.ACCESS_TOKEN}} ghcr.io
                docker build -t ghcr.io/sohamping/arithmetic-service:latest --file Dockerfile .  
                docker push ghcr.io/sohamping/arithmetic-service:latest 
            - name: Build and push the image
              run: |
                docker login --username practicum15SP --password ${{secrets.AZURE_CONTAINER_REGISTRY}} practicum15sp.azurecr.io
                docker tag ghcr.io/sohamping/arithmetic-service:latest practicum15sp.azurecr.io/arithmetic-service:latest 
                docker push practicum15sp.azurecr.io/sohamping/arithmetic-service:latest 